### ISSUE TITLE
Error on iOS safari

### ISSUE THREAD

**Issue by iShawnWang** [dev-judsoncruz/react-navigator-geoposition#2]
### device
- iOS 13.4.1
- iPhone XR

![image](https://user-images.githubusercontent.com/20266594/83710515-84478f00-a653-11ea-8d4e-7f5a3ab7d487.png)

**Comment by jsoncruz** [comment]
**Update 1.0.8**

It prevents error exception if the device doesn't support geolocation permission API
You can check if your device has support to navigator geolocation
[Read more](https://developer.mozilla.org/en-US/docs/Web/API/Permissions/query)

**Comment by iShawnWang** [comment]
awesome ~

**Comment by mitas1** [comment]
I'm not sure If I understood, so this should be fixed in **1.0.8** ? I'm getting this error in Safari Version 14.0.3 (16610.4.3.1.4) mac OS 11.2.

**Comment by reiui9** [comment]
Same error on 1.0.8 version
